/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAvaliacaoRouteImport } from './routes/_authenticated/avaliacao'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEquipesRouteImport } from './routes/_authenticated/equipes'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedNovaIdeiaRouteImport } from './routes/_authenticated/nova-ideia'
import { Route as AuthenticatedOkrsRouteImport } from './routes/_authenticated/okrs'
import { Route as AuthenticatedPessoasRouteImport } from './routes/_authenticated/pessoas'
import { Route as AuthenticatedIdeiasIdRouteImport } from './routes/_authenticated/ideias.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvaliacaoRoute = AuthenticatedAvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipesRoute = AuthenticatedEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaIdeiaRoute = AuthenticatedNovaIdeiaRouteImport.update({
  id: '/nova-ideia',
  path: '/nova-ideia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOkrsRoute = AuthenticatedOkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPessoasRoute = AuthenticatedPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeiasIdRoute = AuthenticatedIdeiasIdRouteImport.update({
  id: '/ideias/$id',
  path: '/ideias/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/avaliacao': typeof AuthenticatedAvaliacaoRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ideia': typeof AuthenticatedNovaIdeiaRoute
  '/okrs': typeof AuthenticatedOkrsRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/ideias/$id': typeof AuthenticatedIdeiasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/avaliacao': typeof AuthenticatedAvaliacaoRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ideia': typeof AuthenticatedNovaIdeiaRoute
  '/okrs': typeof AuthenticatedOkrsRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/ideias/$id': typeof AuthenticatedIdeiasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/avaliacao': typeof AuthenticatedAvaliacaoRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/equipes': typeof AuthenticatedEquipesRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/nova-ideia': typeof AuthenticatedNovaIdeiaRoute
  '/_authenticated/okrs': typeof AuthenticatedOkrsRoute
  '/_authenticated/pessoas': typeof AuthenticatedPessoasRoute
  '/_authenticated/ideias/$id': typeof AuthenticatedIdeiasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/avaliacao'
    | '/categorias'
    | '/equipe'
    | '/equipes'
    | '/inicio'
    | '/notificacoes'
    | '/nova-ideia'
    | '/okrs'
    | '/pessoas'
    | '/ideias/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/avaliacao'
    | '/categorias'
    | '/equipe'
    | '/equipes'
    | '/inicio'
    | '/notificacoes'
    | '/nova-ideia'
    | '/okrs'
    | '/pessoas'
    | '/ideias/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/avaliacao'
    | '/_authenticated/categorias'
    | '/_authenticated/equipe'
    | '/_authenticated/equipes'
    | '/_authenticated/inicio'
    | '/_authenticated/notificacoes'
    | '/_authenticated/nova-ideia'
    | '/_authenticated/okrs'
    | '/_authenticated/pessoas'
    | '/_authenticated/ideias/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avaliacao': {
      id: '/_authenticated/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AuthenticatedAvaliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes': {
      id: '/_authenticated/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthenticatedEquipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ideia': {
      id: '/_authenticated/nova-ideia'
      path: '/nova-ideia'
      fullPath: '/nova-ideia'
      preLoaderRoute: typeof AuthenticatedNovaIdeiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/okrs': {
      id: '/_authenticated/okrs'
      path: '/okrs'
      fullPath: '/okrs'
      preLoaderRoute: typeof AuthenticatedOkrsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas': {
      id: '/_authenticated/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AuthenticatedPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ideias/$id': {
      id: '/_authenticated/ideias/$id'
      path: '/ideias/$id'
      fullPath: '/ideias/$id'
      preLoaderRoute: typeof AuthenticatedIdeiasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvaliacaoRoute: typeof AuthenticatedAvaliacaoRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEquipesRoute: typeof AuthenticatedEquipesRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovaIdeiaRoute: typeof AuthenticatedNovaIdeiaRoute
  AuthenticatedOkrsRoute: typeof AuthenticatedOkrsRoute
  AuthenticatedPessoasRoute: typeof AuthenticatedPessoasRoute
  AuthenticatedIdeiasIdRoute: typeof AuthenticatedIdeiasIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvaliacaoRoute: AuthenticatedAvaliacaoRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEquipesRoute: AuthenticatedEquipesRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovaIdeiaRoute: AuthenticatedNovaIdeiaRoute,
  AuthenticatedOkrsRoute: AuthenticatedOkrsRoute,
  AuthenticatedPessoasRoute: AuthenticatedPessoasRoute,
  AuthenticatedIdeiasIdRoute: AuthenticatedIdeiasIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
